//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseHistory
    {
        public int PurchaseID { get; set; }
        public int UserID { get; set; }
        public int CruiseID { get; set; }
    
        public virtual Cruise Cruise { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
