//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDAC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDatabaseEntities : DbContext
    {
        public MyDatabaseEntities()
            : base("name=MyDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserData> UserDatas { get; set; }
        public virtual DbSet<Cruise> Cruises { get; set; }
        public virtual DbSet<Destination> Destinations { get; set; }
        public virtual DbSet<Port> Ports { get; set; }
        public virtual DbSet<Ship> Ships { get; set; }
        public virtual DbSet<PurchaseHistory> PurchaseHistories { get; set; }
    }
}
